name: ${project.name}
main: ru.soknight.lib.plugin.SKLibraryPlugin
author: SoKnight
version: ${project.version}
load: startup
libraries:
- org.postgresql:postgresql:42.3.3
api-version: 1.13

commands:
  sklibrary:
    description: Display plugin information

permissions:
  sklibrary.command.info:
    default: true